apiVersion: v1
kind: Service
metadata:
  name: deploylens-sample
  namespace: deploylens
  labels:
    app.kubernetes.io/name: deploylens-sample
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: deploylens-sample
  ports:
    - name: http
      port: 80
      targetPort: http
